/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import app.Application;

//import static org.junit.Assert.*;

public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.());
    }
}
